[phases.setup]
nixPkgs = ["python311", "curl"]

[phases.install]
cmds = [
  "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python get-pip.py",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt",
  "rm get-pip.py"
]

[start]
cmd = "cd server && python -m uvicorn server.main:app --host 0.0.0.0 --port $PORT"

